---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.6.2

platforms:
  - name: ubuntu-12.04
    driver_config:
      customize:
        memory: 768
        cpus: 1

suites:
  - name: default
    run_list:
      - recipe[practicingruby::default]
    attributes:
      practicingruby:
        deploy:
          ssh_keys:
            - some-deploy-key
      postgresql:
        password:
          postgres: practicingruby
